<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWCqvBDT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWCqvBDT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWCqvBDT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWCqvBDT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWCqvBDT\App_KernelDevDebugContainer([
    'container.build_hash' => 'WCqvBDT',
    'container.build_id' => 'f5cada24',
    'container.build_time' => 1711591918,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWCqvBDT');
